juanjoGonDev/fastypest

.vscode/settings.json, jest.config.json, package.json, src/core/fastypest.ts, src/core/sql-script/queries/cockroachdb.json, src/core/sql-script/queries/mysql.query.json, src/core/sql-script/queries/postgres.query.json, src/core/sql-script/sql-script.ts, tests/__tests__/simple.spec.ts, tests/config/index.ts, tests/config/jest.setup.ts, tests/config/orm.config.ts, tests/config/seed.config.ts, tests/entities/index.ts, tests/entities/simple.entity.ts, tests/entities/user.entity.ts, tests/seeds/index.ts, tests/seeds/seed.ts, tests/seeds/simple.seed.ts, tests/seeds/user.seed.ts, tests/utils/connection.util.ts, tests/utils/index.ts
**Improve tests**
- I have added seeds with foreign keys
- Now build and use the build for tests
=> feat: improve test

.pnp.cjs, package.json
The version of the code has been bumped to **v1.3.1**
=> Release v1.3.1

CHANGELOG.md, package.json
=> Bump version to v1.3.2

CHANGELOG.md, package.json
=> Bump version to v1.3.4

CHANGELOG.md, package.json
=> Bump version to v1.3.5

CHANGELOG.md, package.json
=> Bump version to v1.3.6

CHANGELOG.md, package.json
=> Bump version to v1.3.7

CHANGELOG.md, package.json
=> Bump version to v1.3.8

CHANGELOG.md, package.json
=> Bump version to v1.3.10

CHANGELOG.md, package.json
=> Bump version to v1.4.1

CHANGELOG.md, package.json
=> Bump version to v1.4.2

CHANGELOG.md, package.json
=> Bump version to v1.4.3

CHANGELOG.md, package.json
=> Bump version to v1.4.4

CHANGELOG.md, package.json
=> Bump version to v1.4.5

CHANGELOG.md, package.json
=> Bump version to v1.4.6

CHANGELOG.md, package.json
=> Bump version to v1.4.7

CHANGELOG.md, package.json
=> Bump version to v1.4.8

CHANGELOG.md, package.json
=> Bump version to v1.4.9

CHANGELOG.md, package.json
=> Bump version to v1.4.10

CHANGELOG.md, package.json
=> Bump version to v1.4.11

CHANGELOG.md, package.json
=> Bump version to v1.4.12

CHANGELOG.md, package.json
=> Bump version to v1.4.13

CHANGELOG.md, package.json
=> Bump version to v1.4.14

CHANGELOG.md, package.json
=> Bump version to v1.4.15

CHANGELOG.md, package.json
=> Bump version to v1.4.16

CHANGELOG.md, package.json
=> Bump version to v1.4.17

CHANGELOG.md, package.json
=> Bump version to v1.4.18

CHANGELOG.md, package.json
=> Bump version to v1.4.19

CHANGELOG.md, package.json
=> Bump version to v1.4.20

CHANGELOG.md, package.json
=> Bump version to v1.4.21

CHANGELOG.md, package.json
=> Bump version to v1.4.22

CHANGELOG.md, package.json
=> Bump version to v1.4.23

CHANGELOG.md, package.json
=> Bump version to v1.4.24

CHANGELOG.md, package.json
=> Bump version to v1.4.26

CHANGELOG.md, package.json
=> Bump version to v1.4.27

CHANGELOG.md, package.json
=> Bump version to v1.4.28

CHANGELOG.md, package.json
=> Bump version to v1.4.29

CHANGELOG.md, package.json
=> Bump version to v1.4.30

CHANGELOG.md, package.json
=> Bump version to v1.4.31

CHANGELOG.md, package.json
=> Bump version to v1.4.32

CHANGELOG.md, package.json
=> Bump version to v1.4.33

CHANGELOG.md, package.json
=> Bump version to v1.4.34

CHANGELOG.md, package.json
=> Bump version to v1.4.35

CHANGELOG.md, package.json
=> Bump version to v1.4.36

CHANGELOG.md, package.json
=> Bump version to v1.4.38

CHANGELOG.md, package.json
=> Bump version to v1.4.39

CHANGELOG.md, package.json
=> Bump version to v1.4.40

CHANGELOG.md, package.json
=> Bump version to v1.4.41

CHANGELOG.md, package.json
=> Bump version to v1.4.42

CHANGELOG.md, package.json
=> Bump version to v1.4.43

CHANGELOG.md, package.json
=> Bump version to v1.4.44

CHANGELOG.md, package.json
=> Bump version to v1.4.45

CHANGELOG.md, package.json
=> Bump version to v1.4.46

CHANGELOG.md, package.json
=> Bump version to v1.4.47

CHANGELOG.md, package.json
=> Bump version to v1.4.48

CHANGELOG.md, package.json
=> Bump version to v1.4.50

CHANGELOG.md, package.json
=> Bump version to v1.4.51

CHANGELOG.md, package.json
=> Bump version to v1.4.52

CHANGELOG.md, package.json
=> Bump version to v1.4.53

CHANGELOG.md, package.json
=> Bump version to v1.4.54

CHANGELOG.md, package.json
=> Bump version to v1.4.55

CHANGELOG.md, package.json
=> Bump version to v1.4.56

CHANGELOG.md, package.json
=> Bump version to v1.4.57

CHANGELOG.md, package.json
=> Bump version to v1.4.58

CHANGELOG.md, package.json
=> Bump version to v1.4.59

CHANGELOG.md, package.json
=> Bump version to v1.4.60

CHANGELOG.md, package.json
=> Bump version to v1.4.61

CHANGELOG.md, package.json
=> Bump version to v1.4.62

CHANGELOG.md, package.json
=> Bump version to v1.4.63

CHANGELOG.md, package.json
=> Bump version to v1.4.64

CHANGELOG.md, package.json
=> Bump version to v1.4.65

CHANGELOG.md, package.json
=> Bump version to v1.4.66

CHANGELOG.md, package.json
=> Bump version to v1.4.67

CHANGELOG.md, package.json
=> Bump version to v1.4.68

CHANGELOG.md, package.json
=> Bump version to v1.4.69

CHANGELOG.md, package.json
=> Bump version to v1.4.70

CHANGELOG.md, package.json
=> Bump version to v1.4.71

CHANGELOG.md, package.json
=> Bump version to v1.4.72

CHANGELOG.md, package.json
=> Bump version to v1.4.73

CHANGELOG.md, package.json
=> Bump version to v1.4.74

CHANGELOG.md, package.json
=> Bump version to v1.4.75

CHANGELOG.md, package.json
=> Bump version to v1.4.77

CHANGELOG.md, package.json
=> Bump version to v1.4.78

CHANGELOG.md, package.json
=> Bump version to v1.4.79

CHANGELOG.md, package.json
=> Bump version to v1.4.80

CHANGELOG.md, package.json
=> Bump version to v1.4.81

CHANGELOG.md, package.json
=> Bump version to v1.4.82

CHANGELOG.md, package.json
=> Bump version to v1.4.83

CHANGELOG.md, package.json
=> Bump version to v1.4.84

CHANGELOG.md, package.json
=> Bump version to v1.4.85

CHANGELOG.md, package.json
=> Bump version to v1.4.87

CHANGELOG.md, package.json
=> Bump version to v1.4.88

CHANGELOG.md, package.json
=> Bump version to v1.4.89

CHANGELOG.md, package.json
=> Bump version to v1.4.90

CHANGELOG.md, package.json
=> Bump version to v1.4.91

CHANGELOG.md, package.json
=> Bump version to v1.4.92

CHANGELOG.md, package.json
=> Bump version to v1.4.93

CHANGELOG.md, package.json
=> Bump version to v1.4.94

CHANGELOG.md, package.json
=> Bump version to v1.4.95

CHANGELOG.md, package.json
=> Bump version to v1.4.96

CHANGELOG.md, package.json
=> Bump version to v1.4.97

CHANGELOG.md, package.json
=> Bump version to v1.4.98

CHANGELOG.md, package.json
=> Bump version to v1.4.99

CHANGELOG.md, package.json
=> Bump version to v1.4.100

CHANGELOG.md, package.json
=> Bump version to v1.4.101

CHANGELOG.md, package.json
=> Bump version to v1.4.102

CHANGELOG.md, package.json
=> Bump version to v1.4.103

CHANGELOG.md, package.json
=> Bump version to v1.4.104

CHANGELOG.md, package.json
=> Bump version to v1.4.106

CHANGELOG.md, package.json
=> Bump version to v1.4.107

CHANGELOG.md, package.json
=> Bump version to v1.4.108

CHANGELOG.md, package.json
=> Bump version to v1.4.110

CHANGELOG.md, package.json
=> Bump version to v1.4.111

CHANGELOG.md, package.json
=> Bump version to v1.4.115

CHANGELOG.md, package.json
=> Bump version to v1.4.116

CHANGELOG.md, package.json
=> Bump version to v1.4.117

CHANGELOG.md, package.json
=> Bump version to v1.4.119

CHANGELOG.md, package.json
=> Bump version to v1.4.120

CHANGELOG.md, package.json
=> Bump version to v1.4.122

CHANGELOG.md, package.json
=> Bump version to v1.4.123

CHANGELOG.md, package.json
=> Bump version to v1.4.125

CHANGELOG.md, package.json
=> Bump version to v1.4.127

CHANGELOG.md, package.json
=> Bump version to v1.4.128

CHANGELOG.md, package.json
=> Bump version to v1.4.129

CHANGELOG.md, package.json
=> Bump version to v1.4.130

CHANGELOG.md, package.json
=> Bump version to v1.4.131

CHANGELOG.md, package.json
=> Bump version to v1.4.132

CHANGELOG.md, package.json
=> Bump version to v1.4.136

CHANGELOG.md, package.json
=> Bump version to v1.4.138

CHANGELOG.md, package.json
=> Bump version to v1.5.2

CHANGELOG.md, package.json
=> Bump version to v1.5.6
